ALL += libsndfile/cve-2021-3246
FULL += libsndfile/cve-2021-3246
SNSCOUNT += libsndfile/cve-2021-3246
RELAX += libsndfile/cve-2021-3246
CONCR += libsndfile/cve-2021-3246

libsndfile/cve-2021-3246.run:
	cd libsndfile && nix-build
