ALL += perl-dbi/cve-2020-14393
FULL += perl-dbi/cve-2020-14393
CFH += perl-dbi/cve-2020-14393
RELAX += perl-dbi/cve-2020-14393
CONCR += perl-dbi/cve-2020-14393

perl-dbi/cve-2020-14393.run:
	echo ""

perl-dbi/cve-2020-14393.nix:
	echo ""

perl-dbi/cve-2020-14393.cfh.nix:
	echo ""

perl-dbi/cve-2020-14393.relax.nix:
	echo ""

perl-dbi/cve-2020-14393.concr.nix:
	echo ""
